// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PdnLesson12.PdnEntities;

#nullable disable

namespace PdnLesson12.Migrations
{
    [DbContext(typeof(PdnAppDbContext))]
    [Migration("20261001130328_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PdnLesson12.Models.PdnCategory", b =>
                {
                    b.Property<int>("PdnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PdnId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdnName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("PdnStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("PdnId");

                    b.ToTable("PdnCategory");
                });

            modelBuilder.Entity("PdnLesson12.Models.PdnProduct", b =>
                {
                    b.Property<int>("PdnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PdnId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PdnCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("PdnDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("ntext");

                    b.Property<string>("PdnImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PdnName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<float>("PdnPrice")
                        .HasColumnType("real");

                    b.Property<float>("PdnSalePrice")
                        .HasColumnType("real");

                    b.Property<byte>("PdnStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("PdnId");

                    b.HasIndex("PdnCategoryId");

                    b.ToTable("PdnProduct");
                });

            modelBuilder.Entity("PdnLesson12.Models.PdnProduct", b =>
                {
                    b.HasOne("PdnLesson12.Models.PdnCategory", "PdnCategory")
                        .WithMany("PdnProducts")
                        .HasForeignKey("PdnCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PdnCategory");
                });

            modelBuilder.Entity("PdnLesson12.Models.PdnCategory", b =>
                {
                    b.Navigation("PdnProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
